### ISSUE TITLE
Should cancel on Smite/Protection remove the AE or apply it without actual effect?

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#10]
I don't know if this is possible (And if not just ignore it.) When you use the build smite effect on SUCC it adds the effect and asks what you want to add the effect to. If you cancel it it still adds the smite with no active effect. Is it possible for the cancel button to remove the half built effect?

**Comment by SalieriC** [comment]
Programming wise the function just alters the effect which is added by Foundry already. I deliberately _not_ removed the effect on cancel to allow players to choose to have the AE without actual effect. I'd be interested in other users opinions what the expected and desirable behaviour would be.

**Comment by SalieriC** [comment]
Due to a lack of response I'll leave it as it is for now. Feel free to open it again if you'd like to add further opinions. =)
