### ISSUE TITLE
Players Get Error whenever condition is applied

### ISSUE THREAD

**Issue by thorgibrewer** [SalieriC/SUCC#15]
My players get the following issue whenever a condition is applied to a combatant. Will test to see if it is only tokens they do not control, but as far as I know it was all the npcs in my game last night. Errors and console attached.
![image](https://user-images.githubusercontent.com/69551564/161771762-fc420905-6656-4f65-854d-56fa9a10ead3.png)
![image](https://user-images.githubusercontent.com/69551564/161771790-41ea7acc-e979-4d96-af84-6e0cd578c688.png)

**Comment by thorgibrewer** [comment]
I'll have to test. I think it was happening on the two we encountered last night: Shaken and Incapacitated

**Comment by SalieriC** [comment]
I assume it's only on Inc due to marking NPCs as dead whilst not checking for GM permission. Please reopen this ticket should it happen on _any_ other condition.
