### ISSUE TITLE
Turning conditions on and off?

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#22]
Is there an option to turn a condition on and off? When you have a AE attached to an item it would be helpful if you could turn it on or off ratehr then removing and adding it again.

**Comment by SalieriC** [comment]
I think I don't quite understand. Active Effects which are on items are transferred to the actor by the system. SUCC then does nothing with them.

**Comment by grendel111111** [comment]
I'm trying to modify the BR2 bad eyes action. So if a character with bad eyes has glasses the effect does not come on. To do this glasses have an active effect of "Wearing_glasses". 
In the rules if they are hit with an attack there is a 50/50 chance their glasses will be knocked off etc. But rather than removing the glasses I was hoping to turn off the active effect, so the bad eyes effect will come back on.

**Comment by SalieriC** [comment]
Why don't you just turn the AE off instead of removing the glasses then?

I honestly don't think changing the core behaviour in this way is in scope of this module, what do you think @javierriveracastro ?

**Comment by grendel111111** [comment]
Yes, I was wondering if there was a way to turn off the AE rather than removing the glasses. But I can't find how to do that through a Macro, so I thought SUCC might have a way to do it already. That way I wouldn't be trying to create something that already exists. As it doesn't I will look into how to tun of the AE by macro.

**Comment by SalieriC** [comment]
```js
let glassesAe = token.actor.effects.find(i => i.label === "Wearing_glasses")
if (glassesAe) {
  await glassesAe.update({"disabled": glassesAe.disabled ? false : true})
}
```
This should toggle the AE of the currently selected tokens actor.

**Comment by grendel111111** [comment]
Thank you.
