### ISSUE TITLE
Vulnerable status does not renew

### ISSUE THREAD

**Issue by basic-element** [SalieriC/SUCC#23]
When apply status for vulnerable gets applied to someone already vulnerable, the duration does not get renewed. I.E. doing a wild attack 1st round causes vulnerable until end of turn in 2nd round. If during turn of 2nd round, I do another wild attack, a new vulnerable status is not added. The old vulnerable status gets removed at the end of turn of 2nd round.

**Comment by SalieriC** [comment]
SUCC itself has no knowledge of when you do which action and thus cannot adjust the condition. The module which applies the condition has to take care of that.

**Comment by javierriveracastro** [comment]
if we don't abstract condition creation for the module, we are a poor library.

I believe that SUCC should offer an optional parameter to set the starting round to modules using it.
