### ISSUE TITLE
Adding multiple conditions sometimes results in duplicate condition icons

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SUCC#24]
After loading a world, the first time conditions are applied - that are by themselves adding other conditions - the condition icons are added multiple times to the token. This does only happen the first time after loading a world. After that it seems to be fine.
Example macro for testing:
```js
await succ.apply_status(token, 'stunned', true)
await succ.apply_status(token, 'distracted', true)
await succ.apply_status(token, 'vulnerable', true)
```

I believe this is new, I don't think this was the case in the v9 version of SUCC. Any idea what is off @javierriveracastro?

[succ.webm](https://user-images.githubusercontent.com/1230041/194785027-e9f563f4-a4b3-4146-ad12-fe2829580259.webm)

**Comment by javierriveracastro** [comment]
No at all. I'll look into it after solving all the new and shinny bugs that v10 has created/surfarce in BR2.

**Comment by SalieriC** [comment]
Seems to be a race condition that happens when a status is applied that activates another status in system but then the same status is again applied via SUCC. We currently have no way to fix it.

**Comment by SalieriC** [comment]
I can't reproduce it any longer. Please reopen if it occurs again.
