### ISSUE TITLE
Prone Active Effects.

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#29]
Is it possible to get active effects added to the prone condition.
"system.stats.parry.modifier", "mode":CONST.ACTIVE_EFFECT_MODES.ADD, "value":"-2"
and
@Skill{Fighting}[ system.die.modifier] ", "mode":CONST.ACTIVE_EFFECT_MODES.ADD, "value":"-2"

(-2 to parry and -2 to your fighting skill.)

**Comment by SalieriC** [comment]
Sure thing, added in git.
Next time please put everything in a code block so you don't mention s/o who is not involved in this. =)
