### ISSUE TITLE
Update the SWPF reference links

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SUCC#3]
As they have messed up the IDs there as well...

**Comment by SalieriC** [comment]
If someone would like to help and see that in the next prerelease version, feel free to fill in the blanks here:
https://github.com/SalieriC/SUCC/blob/786d3d876d8833e6496e780fff08ce6dfc88aefa/succ/scripts/default_mappings.js#L137-L163

**Comment by nchiasson** [comment]
export const SUCC_DEFAULT_SWPF_LINKS_NEW = {
	//These are the compendium links for the entries in the Savage Pathfinder Core Rules Module
    'shaken': '@Compendium[swpf-core-rules.swpf-rules.QTDpA978FoGy0P3k]',
    'incapacitated': '@Compendium[swpf-core-rules.swpf-rules.lXS1wuvs9W779bGk]',
    'aiming': '@Compendium[swpf-core-rules.swpf-rules.Xg9Yy4S7DJIZoC3y]',
    'berserk': '@Compendium[swpf-core-rules.swpf-edges.TjR4gwORZ7E82Wqr]',
    'defending': '@Compendium[swpf-core-rules.swpf-rules.X8svEW536smwgrq6]',
    'flying': '@Compendium[swpf-core-rules.swpf-abilities.lZVhdNhW8bG0GcVz]',
    'holding': '@Compendium[swpf-core-rules.swpf-rules.76sT257yFavaXoqT]',
    'bound': '@Compendium[swpf-core-rules.swpf-rules.bwF5pzEwQSXAYlEb]',
    'entangled': '@Compendium[swpf-core-rules.swpf-rules.bwF5pzEwQSXAYlEb]',
    'frightened': '@Compendium[swpf-core-rules.swpf-rules.xyuYSRJHwsNIsQcH]',
    'distracted': '@Compendium[swpf-core-rules.swpf-rules.1tH7slDGScGgCMfx]',
    'encumbered': '@Compendium[swpf-core-rules.swpf-rules.7STCq0HPoAlaoOZ7]',
    'prone': '@Compendium[swpf-core-rules.swpf-rules.sEybdrp4m3RBl08B]',
    'stunned': '@Compendium[swpf-core-rules.swpf-rules.IJaHhmhsGYz2yDrG]',
    'vulnerable': '@Compendium[swpf-core-rules.swpf-rules.1tH7slDGScGgCMfx]',
    'bleeding-out': '@Compendium[swpf-core-rules.swpf-rules.vJA1HKIF2a34cRYd]',
    'diseased': '@Compendium[swpf-core-rules.swpf-rules.DqEfiYnnjJqBUb0b]',
    'heart-attack': '@Compendium[swpf-core-rules.swpf-rules.xyuYSRJHwsNIsQcH]',
    'on-fire': '@Compendium[swpf-core-rules.swpf-rules.UK0GSlV6M7BYYooQ]',
    'poisoned': '@Compendium[swpf-core-rules.swpf-rules.K2i9FQnRwcPO7Tjo]',
    'cover-shield': '',
    'cover': '@Compendium[swpf-core-rules.swpf-rules.n9yodHBw85sUOGhS]',
    'reach': '@Compendium[swpf-core-rules.swpf-rules.Gv6C7S5II2rHp84I]',
    'torch': '@Compendium[swpf-core-rules.swpf-rules.StKylZawGhVutsR8]',
    'invisible': '@Compendium[swpf-core-rules.swpf-powers.FKymxmrz9ugwfFmb]',
    'smite': '@Compendium[swpf-core-rules.swpf-powers.LiY5yCQkOOKz9T2L]',
    'protection': '@Compendium[swpf-core-rules.swpf-powers.4yGOUiND8lW5cKly]'
}

Pathfinder has an actual compendium header for encumberance (See Below) instead of using the Gear heading which I used in the above list
	'encumbered': '@Compendium[swpf-core-rules.swpf-rules.HazvTAWCK8sclzSF]',
They also removed the shields (cover-shield)compendium heading and rolled them into the Armor heading (See Below)
	'cover-shield': '@Compendium[swpf-core-rules.swpf-rules.oRihpCsgXjbVEOHx]',

**Comment by SalieriC** [comment]
Thanks a lot, I integrated it. I sure hope the user compendium doesn't mind. 🤣
