### ISSUE TITLE
Suggestion: Add time to expiring active effect.

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#34]
Currently time is added in rounds. Can seconds be added as well? (rounds*6). It will make no difference if you don't use times up/ time management, but if you are using them it adds 2 things. If the combat ends you don't need to go through and delete any outstanding AE from the combat as they will disappear after 6-12 seconds (OR move time forward 30sec. and they will all turn off). It will also give a back up if someone puts an AE on before the combat starts.

**Comment by SalieriC** [comment]
I wonder if this is sensible. I know I do this in SWIM but I wonder how usable this is. Most will handle duration out of combat differently I think, let alone the fact that 30 seconds is nothing when describing what you do. Arguably, people who use such modules should know what they are doing.
It won't hurt to add that I suppose, just a few lines, I'm just curious: Do you really use this for SWADE? How? Why?

**Comment by grendel111111** [comment]
What I find it does is that if you end an encounter and there are still active effects running you need to go though all characters and  remove any remaining AE that haven't expired yet. If they have a seconds time and you are using times up or simmilar module, then when the combat ends in a few seconds any remaining effects are removed quickly. I end up just making my own effects and use the succ images so it has the time expire.

**Comment by grendel111111** [comment]
Unless it benefits someone else I wouldn't bother with it.

**Comment by SalieriC** [comment]
I've just pushed something that isn't exactly what you wanted but does serve the same purpose. We settled on this as the team. As with your other ticket, you can manually change the condition effects easily yourself with the next version.
We implemented an api function you can call with `game.succ.removeTemporaryEffects()` in the upcoming version. This will remove every AE from all tokens on the current scene but only those AEs which have a duration set in rounds. You can either set up a macro to call this manually after combat or use a module that allows you to run a function after combat ends. SWIM will soon integrate that feature as well. Optional parameters are `sceneId` (ID of the scene you want to take the tokens from) and `confirmed` (a boolean that lets you skip the confirmation dialogue).

![image](https://github.com/SalieriC/SUCC/assets/1230041/ba0b4303-2b86-4085-af8f-8cc946f4d8e1)

Hope this is helpful.

**Comment by grendel111111** [comment]
That's great thanks. Will it remove active effects only from SUCC or all effects?

**Comment by SalieriC** [comment]
It'll remove all AEs which have a duration set in rounds, even those created in SWIM or by yourself. It ignores turns and seconds. If no duration in rounds is set, then it will not remove the effect. So be careful with it. SWIM comes with the option to run that function after combat ends in the next version as well.
