### ISSUE TITLE
Stun/Shake/Bleedout removal dialogue is set as an IC chat message.

### ISSUE THREAD

**Issue by Buuuurce** [SalieriC/SUCC#35]
The messages to unshake/unstun appear as IC messages in contrast to rolls, soak prompts and damage. 
It's pretty annoying for text based games that use Tabbed Chatlog  to separate IC chat and rolls and very annoying for games that use something like Vino that makes chat messages pop up on the screen.

I can disable the option, but it's a notable loss of convenience.

**Comment by SalieriC** [comment]
Thank you for your submission.
I'm sorry but I have absolutely no idea what you want to tell me, what the problem really is and what you want us to do to fix it. Please elaborate, especially on the abbreviation "IC".

**Comment by Buuuurce** [comment]
> Thank you for your submission. I'm sorry but I have absolutely no idea what you want to tell me, what the problem really is and what you want us to do to fix it. Please elaborate, especially on the abbreviation "IC".

By IC I mean mean "In Character".

I'd like for someone to change the roll type setting so the unshake/un-x messages are treated as roll messages and not as In Character messages.

Here's an image showing how the module acts with the Tabbed Layout module that separates the different types of chat messages. 
![Foundry_Virtual_Tabletop_xBgL5WiOHZ](https://user-images.githubusercontent.com/116317399/207608429-ce3098c4-ddfb-4d6d-b3b1-e3c35e54de0c.png)

**Comment by SalieriC** [comment]
In this screenshot there is only one message from SUCC: The one notifying about the added shaken effect. That isn't what you mean, is it?

If it is not I am unable to help you here for two reasons: Mainly because there is no other message from SUCC is present here. But also because I don't know the module that changes the chat and don't know if I can/want to support it.

**Comment by Buuuurce** [comment]
> In this screenshot there is only one message from SUCC: The one notifying about the added shaken effect. That isn't what you mean, is it?
> 
> If it is not I am unable to help you here for two reasons: Mainly because there is no other message from SUCC is present here. But also because I don't know the module that changes the chat and don't know if I can/want to support it.

Yes, that shaken effect message is what I mean. I didn't screenshot them but the notifications about Conditions being put into chat show up as rolls and that is what I'd like the unshake messages to show up as.

Also this isn't solely about tabbed layout but about other text based gaming related modules like Vino and Theater Inserts that rely on a separation of what Foundry considers In Character messages and what it considers rolls as well as a general consistency issue.

**Comment by javierriveracastro** [comment]
That's a better rolls message and should be already be solved in version 3.13.

Closing it as it is not SUCC related.
