### ISSUE TITLE
manifest issue

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#36]
Hi 

update generates this every time

![image](https://user-images.githubusercontent.com/4999783/233099802-3242d655-058b-4ba0-9980-040d435490c6.png)

**Comment by javierriveracastro** [comment]
This is because there is a zip, but  not a manifest on the release and the manifest has changed in github.

Should be solved when a new release is made, hopefully this weekend.

**Comment by brunocalado** [comment]
Everytime you hit update you got this module to update. 

![image](https://github.com/SalieriC/SUCC/assets/4999783/9c745bce-91c3-43bf-ade8-e8f72f32de08)

Can I suggest to update  verified to 11, so no warnings over fvtt updates on v11
  "compatibility": {
    "minimum": "11",
    "verified": "11"
  },

Also, the problem should be in your fvtt site package configuration. I don't know what can be.
![image](https://github.com/SalieriC/SUCC/assets/4999783/19d3106c-5ca2-42d0-a002-a7a59f142943)
