### ISSUE TITLE
Links to SWADE core are broken

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#4]
Both on and off Forge when you add a condition there used to be links to the core rules which are now showing as broken.
Using foundry9 build:249 swade 1.0.4, core rules 1.0.6, SUCC 0.1.0 pre2.

![image](https://user-images.githubusercontent.com/80164119/155828203-1c78610d-5560-4e55-bf8a-649c3ea2c218.png)

**Comment by SalieriC** [comment]
Found it. Apparently `.data.version` is only deprecated for game, not modules. Ah, I really _love_ this deprecation bs... -.-
Anyway, I've made a stealth update for this. Uninstall and reinstall, then it should work.

**Comment by grendel111111** [comment]
Even with a reinstall it doesn't seem to be working. I am on the Forge so that might not have updated

**Comment by SalieriC** [comment]
Which swade core version are you on?

**Comment by javierriveracastro** [comment]
There is also another complain ni the discord channel. Probably the last core rules update broke the links again.

**Comment by SalieriC** [comment]
I sure hope they got back to the original links. Otherwise I'll be furious. XD

**Comment by grendel111111** [comment]
![image](https://user-images.githubusercontent.com/80164119/159280484-d43e001e-f61e-4ff0-960a-325e890d8d9d.png)

**Comment by grendel111111** [comment]
1.0.7 (sorry that would make more sense)

**Comment by SalieriC** [comment]
That explains it then. I suppose they got back to the original IDs. Could you give me the ID of one of them? Maybe `Damage Effects` please? You can find it if you drag it from your compendium to an empty journal you're editing and copying the link that will be created.

**Comment by grendel111111** [comment]
@Compendium[swade-core-rules.swade-rules.HM1iVVbYciEa7X57]{Damage Effects}

**Comment by SalieriC** [comment]
Oh gosh, I hate them. -.-
They have not changed the IDs at all it seems.
