### ISSUE TITLE
Icons Broken Links

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#41]
Hi.

Some icons are broken:
![image](https://github.com/SalieriC/SUCC/assets/4999783/66488d37-3bb4-4ab1-8e81-dec073f71022)

Thank you.

**Comment by ddbrown30** [comment]
I can see that the path is wrong for those two conditions. I'm guessing you have some bad data for some reason, although I'm not sure how you got into that state. You should be able to fix that by clicking Restore Defaults.

**Comment by brunocalado** [comment]
> I can see that the path is wrong for those two conditions. You're in a bad state for some reason, although I'm not sure how it happened. You should be able to fix that by clicking Restore Defaults.

Thank you. Worked.
