### ISSUE TITLE
Use of  flags.core.statusId on an Active Effects is deprecated and will be removed in v13

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SUCC#49]
Applying the Distracted status using `succ.apply_status(selectedtoken, 'distracted', true)` works fine.

However the console shows an error ...
_Error: You are setting flags.core.statusId on an Active Effect. This flag is deprecated in favor of the statuses set.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13_

![image](https://github.com/SalieriC/SUCC/assets/64320/5b22539a-5520-46bc-9412-a101a87acbca)

**Comment by ddbrown30** [comment]
This isn't a bug in SUCC, its a bug in SWIM. This does not happen if SWIM is disabled and I'm still able to get it even with SUCC disabled (even though SUCC is technically a dependency).

**Comment by ddbrown30** [comment]
@SalieriC Every place you're using condition.flags?.core?.statusId has to be changed. Those are the lines that cause the deprecation error.
