### ISSUE TITLE
Enhance the contrast between the addition of a status and the removal of a status

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SUCC#55]
The existing dialog only has the difference between a "+" and a "-" as the indication of the addition or removal of a status.

![image](https://github.com/SalieriC/SUCC/assets/64320/6dc4671e-f304-442c-966e-269469d040f8)

Could the difference be enhanced, e.g. by shading the background, say light red for gaining the status, and light green for removal

![image](https://github.com/SalieriC/SUCC/assets/64320/9948a9b5-853b-4d4d-b22b-c61133f47bdc)

**Comment by SalieriC** [comment]
With conditions being either positive or negative, green and red can be confusing. We thought about other colours but in the end we decided against it for now. I am thinking of alternatives to make it more clear but haven't found good ones yet. I will close this for now but keep it in mind if I find a better solution. Please don't hesitate to reopen this if you can think of a good alternative.
