### ISSUE TITLE
Feature Request: Ownership to View Custom Conditions

### ISSUE THREAD

**Issue by JasonSK22** [SalieriC/SUCC#58]
SUCC is awesome.  I am using it quite a bit for things like vision detection mode changes, Dragon shape changing, Tattoo Armor for Tattoo Warriors from rifts.  It is working great.  The ability to activate a macro or add an AE off a conditions change is a game changer.

Is it possible to add Ownership Configuration to custom conditions?  The reason I ask is the conditions box is filling up with custom conditions that are geared to certain players/characters and it would be nice to only display conditions relevant to a player's character.

**Comment by SalieriC** [comment]
Pretty difficult but also rather specific I think. If it is something specific to just a select few it's probably not a good fit for a condition. Possibly better suited for a macro to apply what you need.

**Comment by JasonSK22** [comment]
I appreciate the feedback and it was worth a discussion.

The less steps a player has to take to active a macro, add an ae, or remove an ae the better.  Ill continue to use the condition lab to add specific actor type conditions.  The setup is working well, just cluttered.

Thanks.
