### ISSUE TITLE
Bug: Infravision / Detect Heat detects "Cold Blooded" tokens

### ISSUE THREAD

**Issue by loofou** [SalieriC/SUCC#60]
### Issue Description

1. Set up token with Infravision and Sense Heat. 
2. Put second token behind wall in detection range.
3. Put status "Cold Blooded" on second token
4. See that token is still detected via Sense Heat.

### Expected Result

"Cold Blooded" token is invisible to tokens using "Detect Heat" only.

This works as expected in system-only, when the server is fully restarted after disabling SUCC.

Not sure if it's a bug or a missing feature, tbh, but Invisibility works as expected at least.

**Comment by SalieriC** [comment]
Should be fixed in git.
