### ISSUE TITLE
Savage Pathfinder Berserk / Rage

### ISSUE THREAD

**Issue by StormDarkwood** [SalieriC/SUCC#67]
I have seen that among the files there is one that deals with Savage Pathfinder: \config\condition-map-module-overrides\swpf-core-rules.json

When running the module on a server on Oracle and on local I see that on one I get a Rage status and on the other I do not. Both systems are updated to the same version of foundry, system and modules.
The Berserker status applies the basic SWADE rules. Couldn't the module be adapted to Savage Pathfinder? 
The Rage state applies absolutely nothing and has no duration.

I have tried to see read the code so I can make changes but I have no idea how to do it.

Thanks

![rage](https://github.com/SalieriC/SUCC/assets/75157840/32cbb71d-6f5a-41ba-be2f-7cac8d16ce6c)

**Comment by SalieriC** [comment]
So just to get this right: The Rage AE currently doesn't apply any changes but should according to the rules, is that right? I don't play SWPF and can't take a look at the rules atm, so I don't know what Rage actually does. But If I got you right, it shouldn't be a problem to add.

**Comment by ddbrown30** [comment]
The system already does handle SWPF (although reading the PF rules I realize now they are slightly different so I'll need to fix that). All it does is rename Berserk to be Rage which means it's actually wrong right now. That said, that doesn't seem to be what you're describing. First, make sure that you don't have both the swade core module and swpf module active at the same time. The override system works just by checking which modules are active so if they're both active, it will have unpredictable behaviour (although I'm pretty sure core ends up taking precedence).

If that's not fixing your problem, please provide me with full repro steps and the list of the minimum number of modules you need active to repro the bug.

**Comment by ddbrown30** [comment]
I figured it out. I'll still need to fix the fact that the SWPF rules are different.

**Comment by SalieriC** [comment]
Done in Git by #68
