### ISSUE TITLE
Remove The Drop

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#81]
Hi. This is a great module. Thank you for your hard work.

I want to suggest to remove the The Drop condition. There is no automation for it and BR2 already treat it as an action.
![image](https://github.com/SalieriC/SUCC/assets/4999783/1987fafb-7696-4222-a164-e53befc2240c)

**Comment by SalieriC** [comment]
Thank you for your suggestion.
If it bothers you, you can just disable it in the modules settings:
![image](https://github.com/SalieriC/SUCC/assets/1230041/ad829257-7761-42e3-a57d-19e7f305a2de)
I see no reason to remove it from the module completely since it can be so easily deactivated.

**Comment by SalieriC** [comment]
Coming back to this. As was pointed out, The Drop isn't a condition in the system anymore so we decided to keep but turn it off by default. This way, anyone who wants it can easily activate it.
