### ISSUE TITLE
status halo

### ISSUE THREAD

**Issue by EternalRider** [SalieriC/SUCC#88]
only [status halo](https://gitlab.com/mxzf/status-halo) :
![image](https://github.com/SalieriC/SUCC/assets/46736326/e0de0591-dfb8-41cd-b077-28e553cf69b1)

status halo and succ :
![image](https://github.com/SalieriC/SUCC/assets/46736326/b2571155-ac1b-4232-bb07-1bfa4bac9d50)

**Comment by EternalRider** [comment]
reason is Token.prototype._refreshEffects

**Comment by ddbrown30** [comment]
I'm going to need more info here especially considering I don't know what the other module is doing. Please give a detailed description of the problem along with steps to reproduce it.

**Comment by EternalRider** [comment]
原因是succ和status halo都覆盖了Token.prototype._refreshEffects方法，导致status halo的令effect环绕token的效果没有生效，而status halo还覆盖了Token.prototype._drawEffect方法改变了effect的mask，进而导致所有的effect都呈现为这种样子。
The reason is that both succ and status halo overwrite the Token.prototype._refreshEffects method. As a result, the effect of status halo surrounding the token is not effective. The status halo also overwrites the Token.prototype._drawEffect method to change the effect's mask, causing all effects to look like this.

我本地使用了一个非常简单粗暴的方法解决，即令succ在检测到开启了status halo这个模组时不会去覆盖Token.prototype._refreshEffects方法，这样就完全使用了status halo这个模组提供的effect显示修改（环状围绕token），而不会使用succ的（根据token大小缩放）。
I use a very crude method to solve this problem, that is, succ does not override Token.prototype. _refreshEffects when it detects that the status halo module is enabled. This makes full use of the effect display modifications provided by the status halo module (loops around the token) and does not use succ's (scaling based on token size).


```
    static patchCore() {
      if (!game.modules.get("status-halo")?.active) {
        Token.prototype._refreshEffects = TokenUtility._refreshEffectsOverride;
      }
    }
```

**Comment by ddbrown30** [comment]
No worries. That should be good enough for me to figure it out. Thanks. :)

**Comment by ddbrown30** [comment]
I actually quite like the way this looks so I'm just going to add support for this to succ directly. This will also let us continue to benefit from the icon size options.

FYI, even with succ disabled, status halo doesn't handle overlay icons correctly (overlay icons are the ones that take up the whole token).

**Comment by EternalRider** [comment]
overlay icons的问题是由于status halo覆盖了Token.prototype._drawEffect方法所导致的，我已经在那边反馈了。
The problem of overlay icons is caused by the status halo overwriting the Token.prototype._drawEffect method. I have given feedback there.

**Comment by SalieriC** [comment]
@ddbrown30 added this feature directly to SUCC and it'll be available in the next version of SUCC.
