### ISSUE TITLE
Adding multiple things through a Macro using SUCC

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#9]
When you apply multiple effects in a macro with SUCC if the token is linked to an actor it will work with no problem. However if you use the same macro on an unlinked token it will only apply one of the effects. Am I missing a step in applying effects to tokens?

**Comment by SalieriC** [comment]
Please always provide a sample on problems like this so I can properly test.
Do you `await` the api functions of SUCC? I do apply multiple things occasionally as well but I think it works just fine.

**Comment by grendel111111** [comment]
I made a video but it won't upload because of size and then format is wrong

https://user-images.githubusercontent.com/80164119/160304490-d1bd4203-096b-40cf-8050-25795965a120.mp4

.

**Comment by SalieriC** [comment]
I would've been fine with just the macro but alright. I can hardly read your macro in that video but I think you don't `await` the SUCC function. This'll get you what you need:
```
await succ.apply_status(token, "bound", true)
await succ.apply_status(token, "aiming", true)
```

**Comment by grendel111111** [comment]
Thanks I was putting the await in the wrong place in my other macro, it is working great now, Thank you,
