### ISSUE TITLE
vehicle has no detail

### ISSUE THREAD

**Issue by EternalRider** [SalieriC/SUCC#90]
![image](https://github.com/SalieriC/SUCC/assets/46736326/4c75c98d-59f9-49bf-aba6-c5320f708d97)

在enhanced-conditions.js这个文件的_onSwadeActorPrepareDerivedData方法里，没有对vehicle类型的actor做处理，导致修改vehicle类型actor的时候会出现这样的报错。
The _onSwadeActorPrepareDerivedData method of the enhanced-conditions.js file, no actor do processing of vehicle types, lead to modify the vehicle type the actor when such an error will occur.

add this can fix it:
```
if (actor.type === "vehicle") {
  return;
}
```

**Comment by ddbrown30** [comment]
I'll leave this one for you to fix, @SalieriC. The crash is because actor.system.details is undefined on vehicle actors but EternalRider's suggested fix seems like the right fix to me given that vehicles shouldn't use encumbrance. Let me know if you need any help.

**Comment by SalieriC** [comment]
I excluded vehicles for now but I think there would be reason to include them. I think they have maximum cargo space in the system, don't they?
