### ISSUE TITLE
[Bug] Add Condition failed. Could not find condition: dead

### ISSUE THREAD

**Issue by r2roberts** [SalieriC/SUCC#91]
**Describe the bug**
When an extra is wounded by Better Rolls 2 for SWADE I get the error:

foundry.js:68326 Add Condition failed. Could not find condition: dead
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
addCondition @ enhanced-conditions-api.js:49
apply_damage @ damage_card.js:171
create_damage_card @ damage_card.js:44
(anonymous) @ item_card.js:403
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
enhanced-conditions-api.js:50 SWADE Ultimate Condition Changer - Enhanced Conditions | Add Condition failed. Could not find condition: dead
enhanced-conditions-api.js:213 SWADE Ultimate Condition Changer - Enhanced Conditions | shaken is not active on token. Remove Condition failed.")
commons.js:8807 Foundry VTT | Created ChatMessage with id [eytv7pxGsBNxpDxq]

**To Reproduce**
- Use BR2 for SWADE module
- Target an extra
- use a weapon to inflict at least one wound
- apply the wound to the target

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.4.1
 - Browser: Chrome
 - FVTT Version: 11.315
 - SWADE System Version: 3.3.11
 - SUCC Version:  3.2.0
 - Other Modules enabled?:  yes
 - Better Rolls 2 for Savage Worlds: 3.7.6
 - 
**Additional context**
I've reset the mapping in the condition lab, and have reset the cache to no avail.

**Comment by javierriveracastro** [comment]
I can confirm it. have they renamed the conditions again in system?

**Comment by r2roberts** [comment]
I tried restoring the mappings to defaults and saving, and it still didn't work. I'm still seeing the problem.
At enhanced-conditions.js, line 939
```
 static lookupConditionById(conditionId, map = null) {
        if (!conditionId) return;

        conditionId = conditionId instanceof Array ? conditionId : [conditionId];

        if (!map) map = Sidekick.getSetting(BUTLER.SETTING_KEYS.enhancedConditions.map);

        const conditions = map.filter(c => conditionId.includes(c.id)) ?? [];

        if (!conditions.length) return null;

        return conditions.length > 1 ? conditions : conditions.shift();
    }
```
conditionId is ['dead'], but the value of map does not have an id entry of 'dead'.
<img width="2037" alt="image" src="https://github.com/SalieriC/SUCC/assets/5421706/db5c4937-a663-4fd1-8ece-1725eb392d23">

**Comment by r2roberts** [comment]
I think the problem is in around line 26 of enhanced-conditions.js in _onReady(). Your comments say one thing, but the code does the opposite.

**Comment by javierriveracastro** [comment]
Yes, that looks like the issue. It is also why it is so elusive.

**Comment by SalieriC** [comment]
Done.
