### ISSUE TITLE
[Bug]  Effects without element img and name

### ISSUE THREAD

**Issue by mrcomac** [SalieriC/SUCC#96]
**Describe the bug**
Hi folks,

I was testing the token HUD for SWADE due to [this issue](https://github.com/mrcomac/token-action-hud-swade/issues/40). The reason for the issue is that when enabled, the SUCC module uses `icon` instead of `img` and `label` instead of `name`. I didn't investigate deeply to see if it's creating new entities or if it is required for some reason, but is it possible to keep it compatible with the current SWADE system? I think those are old elements, and the system currently uses new ones.

**To Reproduce**
1. Enable the token HUD
2. Enable the SUCC

**Expected behavior**
Keep compatibility to the swade system.

**Screenshots**
[there is a image in the original issue](https://private-user-images.githubusercontent.com/62338951/354431980-1ac474aa-cc80-4d93-9821-1dd31c32098c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTY3NjMsIm5iZiI6MTcyMjc5NjQ2MywicGF0aCI6Ii82MjMzODk1MS8zNTQ0MzE5ODAtMWFjNDc0YWEtY2M4MC00ZDkzLTk4MjEtMWRkMzFjMzIwOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE4MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYWZkYmRiOGUyYjcyMTdkNDc5ZDI0OTIxNjc1MzQ1MjA3ZjM4MWQ1MzE3Mzk4ZGYyZTIxMDdhNjAxNTZjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6S1vNmVGwD-Y87NfUcNP2DoGH_k7p0nPZYC075sHIS8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - FVTT Version: 12.330
 - SWADE System Version: 4.0.5
 - SUCC Version:  3.3.2
 - Other Modules enabled?:  yes - Token Action HUD for swade

**Additional context**
N/A

**Comment by jasharen** [comment]
Same issue here, and essentially the same version information.

**Comment by ddbrown30** [comment]
This is a bug in the Token Action HUD swade module. Caused by this commit: https://github.com/mrcomac/token-action-hud-swade/commit/e4c46f6cbb8f3736dc66b9a53b2ff04baf791382

I've replied on the original issue.

**Comment by ddbrown30** [comment]
If you grab version 1.1.0 of token-action-hud-swade, it will fix the issue for you.

https://github.com/mrcomac/token-action-hud-swade/releases/tag/1.1.0

**Comment by ddbrown30** [comment]
Never mind. I was doing something dumb. I'll fix it.
