### ISSUE TITLE
[Question] Access to the custom effects/statuses added by SUCC

### ISSUE THREAD

**Issue by mrcomac** [SalieriC/SUCC#98]
**Is your feature request related to a problem? Please describe.**
Howdy,

It's me again requesting another thing, this time not sure if i'm doing something wrong or what. That is the reason i'm not sure if this is a feature request or I just need to learn how to use the API.

Both token HUDs (Argon and Action Token) are able to toggle statuses and effects. The Argon HUD is listening all effects available within the world, including those added by SUCC (this behaviour i need to migrate to the action token hud in the future).

Checking the SUCC's api I can see some options to add and remove conditions, also there is an option to toggle conditions. however, those aren't working. For example, I can't toggle/add the condition defeated to a token, I saw there is a specific method to toggle that condition. Below is the logic that i'm planning to use.
```
const data = await game.swade.util.getStatusEffectDataById(itemId);
if((typeof data) != "undefined") {
    await this.actor.toggleStatusEffect(data.id, {overlay: false})
} else if ( <A CHECK TO VALIDATE IF THAT IS A CONDITION/EFFECT FROM SUCC> ) {
    //game.succ.addCondition(item.name, this.actor); <-- didn't work for defeated
    //game.succ.toggleCondition(item.name, this.actor); <-- also didn't work for defeated
}
```

Error:
```
ENHANCED_CONDITIONS.HasCondition.Failed.NoMapping
foundry.js:72040 Add Condition failed. Could not find condition: Defeated
```

Can you please help me understand how can I implement this functionality in the HUDs? The defeated is just an example, I have a list of effects that Jared kindly listed in [this issue](https://github.com/mrcomac/enhancedcombathud-swade/issues/19).

**Describe the solution you'd like**
I would like to delegate to toggleCondition steps to validate which condition i want to toggle. This way, how to deal with those conditions will be incapsuled by SUCC. 

**Describe alternatives you've considered**
I can implement a logic in the HUDs if possible, however i need some help to understand how it works.

**Additional context**
For reference, I have a issue in my queue regarding this https://github.com/mrcomac/enhancedcombathud-swade/issues/19.

**Comment by SalieriC** [comment]
It's probably not finding the 'Defeated' condition because the condition ID is always lower case. `item.name.toLowerCase()` might work. Depending on the item you're using it might actually be worth considering to use `item.system.swid` instead, as the SWID won't easily change. Of course this will break things if the SWID is not a valid condition ID.
The documentation is currently available here: https://github.com/SalieriC/SUCC/blob/main/succ/API.md
I didn't got around moving it to the wiki yet. Let us know if this answers your question.

**Comment by ddbrown30** [comment]
You shouldn't be required to use the SUCC API to add/remove/toggle conditions unless you are trying to do something specific e.g. you are building something that works around the defeated/death flow. If you just need to toggle conditions in a generic fashion (i.e. you have an array of conditions, which is how TAH works and I assume Argon's is the same), this should work exactly the same as if you were working with default Foundry.

SUCC works simply by replacing CONFIG.statusEffects and listening to the related hooks.

**Comment by mrcomac** [comment]
Hi @SalieriC / @ddbrown30 

I agree that the item's name in lowercase is the id, and i've been using it, however there are few edge cases :/ for example, `defeated`. Its name is `Defeated` and its id is `dead` :/.

I've changed the logic to deal with the ids instead names in lowercase :)

Thank you for helping me

**Comment by SalieriC** [comment]
I think dead is the id we inherited from the system. Not sure they chose it or had to deal with core restrictions here. Can't do anything about it though, we just roll with it.

**Comment by mrcomac** [comment]
@SalieriC i don't think SUCC needs to do anything about that. the HUD that needs to use the item's id.

**Comment by ddbrown30** [comment]
Yeah, you got it. Just switch to using the id instead of the name and you should be good to go. The name isn't safe to use even without the dead/defeated thing as the name is localized.
